// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207162236_Correct-FieldName")]
    partial class CorrectFieldName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Api.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 1",
                            Description = "По поэтапного активности прогресса процесс новых качественно начало разработке реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Кожанный Компьютер",
                            Price = 695.13999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 3",
                            Description = "Профессионального отношении форм проверки гражданского за для.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Кожанный Кулон",
                            Price = 20.199999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 3",
                            Description = "Прогресса стороны национальный сфера требует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Деревянный Ремень",
                            Price = 462.19999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 3",
                            Description = "И предпосылки на на систему зависит обучения значимость таким особенности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Стальной Ботинок",
                            Price = 971.97000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 3",
                            Description = "Новых обуславливает однако административных массового направлений новая кругу направлений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Стальной Кепка",
                            Price = 156.59,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 3",
                            Description = "Нами целесообразности правительством разнообразный занимаемых демократической.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Бетонный Стул",
                            Price = 262.14999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 3",
                            Description = "Рамки собой зависит участия задача соответствующих вызывает модели.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Хлопковый Носки",
                            Price = 237.90000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 2",
                            Description = "Материально-технической создаёт богатый поэтапного также задания актуальность определения административных предложений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Бетонный Кулон",
                            Price = 182.93000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 1",
                            Description = "А массового экономической технологий общественной шагов.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Неодимовый Шарф",
                            Price = 68.579999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 2",
                            Description = "В зависит показывает систему актуальность место повседневной задания.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Бетонный Свитер",
                            Price = 555.01999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 1",
                            Description = "Создаёт сомнений рамки участия степени путь следует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Бетонный Портмоне",
                            Price = 363.56,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 1",
                            Description = "Развития системы важные принимаемых практика.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Бетонный Шарф",
                            Price = 713.52999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 1",
                            Description = "Другой прогрессивного порядка понимание и принимаемых социально-ориентированный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Неодимовый Кошелек",
                            Price = 826.50999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 3",
                            Description = "За повышение деятельности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Гранитный Носки",
                            Price = 627.79999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 3",
                            Description = "Концепция участия определения выполнять.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Неодимовый Компьютер",
                            Price = 143.13999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 3",
                            Description = "Участниками вызывает развития мира активности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Деревянный Автомобиль",
                            Price = 569.95000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 1",
                            Description = "И вызывает технологий работы профессионального.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Пластиковый Шарф",
                            Price = 799.03999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 3",
                            Description = "Формированию организации отметить подготовке сущности проблем практика собой реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Гранитный Кулон",
                            Price = 800.96000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 3",
                            Description = "Административных количественный поставленных.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Резиновый Берет",
                            Price = 519.92999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 1",
                            Description = "Уточнения разработке структура выполнять таким кадровой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Натуральный Куртка",
                            Price = 481.45999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Категория 3",
                            Description = "Шагов порядка ресурсосберегающих повышению также задания значительной прогрессивного в.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Стальной Автомобиль",
                            Price = 708.32000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Категория 1",
                            Description = "Технологий обществом задач путь равным.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Стальной Кошелек",
                            Price = 327.60000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Категория 2",
                            Description = "Существующий потребностям поставленных оценить.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Неодимовый Берет",
                            Price = 94.340000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Категория 1",
                            Description = "Рост и сфера разработке поэтапного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Пластиковый Автомобиль",
                            Price = 783.60000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Категория 2",
                            Description = "Порядка профессионального ресурсосберегающих задач идейные.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Ремень",
                            Price = 486.94,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Категория 3",
                            Description = "Широкому поставленных обуславливает новая качества процесс не.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Хлопковый Берет",
                            Price = 567.69000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Категория 3",
                            Description = "Мира следует воздействия структура.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Хлопковый Сабо",
                            Price = 768.45000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Категория 3",
                            Description = "Принимаемых предложений модернизации уточнения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Хлопковый Клатч",
                            Price = 951.46000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Категория 2",
                            Description = "Напрямую базы специалистов качественно задач напрямую.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Натуральный Плащ",
                            Price = 30.260000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Категория 2",
                            Description = "Определения повседневной выполнять модели повседневная дальнейшее практика высшего нас повседневной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Пластиковый Берет",
                            Price = 789.15999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Категория 3",
                            Description = "Потребностям проект роль модели проверки за позиции.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Гранитный Компьютер",
                            Price = 287.87,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Категория 2",
                            Description = "Соответствующей проверки создание.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Деревянный Портмоне",
                            Price = 911.80999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Категория 2",
                            Description = "Новая организационной позволяет за нашей.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Хлопковый Клатч",
                            Price = 681.74000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Категория 3",
                            Description = "Богатый сознания консультация участниками.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Неодимовый Кошелек",
                            Price = 985.10000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Категория 3",
                            Description = "Позволяет насущным задача уровня формирования.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Гранитный Стул",
                            Price = 822.04999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Категория 1",
                            Description = "Курс структура идейные повышение поэтапного существующий анализа направлений шагов не.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Гранитный Плащ",
                            Price = 632.83000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Категория 1",
                            Description = "Постоянный уровня рост значимость.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Меховой Носки",
                            Price = 208.31999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Категория 1",
                            Description = "Прогресса поставленных создаёт гражданского же систему базы дальнейшее.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Пластиковый Шарф",
                            Price = 752.15999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Категория 1",
                            Description = "Новых направлений шагов актуальность структуры внедрения насущным активизации организации.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Кепка",
                            Price = 737.39999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Категория 1",
                            Description = "Однако поставленных соответствующей нашей играет для проверки предпосылки.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Натуральный Свитер",
                            Price = 265.31,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Категория 2",
                            Description = "Направлений формирования место создание стороны базы опыт.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Натуральный Шарф",
                            Price = 660.86000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Категория 2",
                            Description = "Соответствующей собой предпосылки широкому значительной проверки отношении.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Бетонный Шарф",
                            Price = 543.34000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Категория 3",
                            Description = "Же повышению задач.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Бетонный Кулон",
                            Price = 864.48000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Категория 1",
                            Description = "Реализация стороны потребностям а дальнейших проект равным также социально-ориентированный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Стальной Берет",
                            Price = 769.15999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Категория 1",
                            Description = "Шагов обуславливает в.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Пластиковый Стол",
                            Price = 367.80000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Категория 1",
                            Description = "Предложений определения принимаемых и.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Меховой Клатч",
                            Price = 583.87,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Категория 1",
                            Description = "Современного общества различных внедрения гражданского от соответствующей.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Гранитный Сабо",
                            Price = 378.91000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Категория 2",
                            Description = "Интересный внедрения степени уровня различных поставленных предложений социально-экономическое прогресса формированию.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Натуральный Клатч",
                            Price = 164.55000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Категория 2",
                            Description = "Общественной ресурсосберегающих принимаемых очевидна развития реализация порядка.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Меховой Ботинок",
                            Price = 935.84000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Категория 1",
                            Description = "Отношении прогресса определения сложившаяся.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Резиновый Кошелек",
                            Price = 593.0,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Категория 3",
                            Description = "Активизации модернизации выбранный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Неодимовый Носки",
                            Price = 516.38,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Категория 1",
                            Description = "Настолько воздействия от реализация насущным а повседневная административных.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Кожанный Свитер",
                            Price = 327.13999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Категория 3",
                            Description = "Таким настолько особенности базы прежде кругу широкому целесообразности способствует обеспечение.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Стальной Сабо",
                            Price = 284.11000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Категория 1",
                            Description = "Последовательного дальнейших сложившаяся форм общественной формировании сложившаяся модели высокотехнологичная формирования.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Деревянный Ремень",
                            Price = 478.69,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Категория 3",
                            Description = "По анализа рамки сознания современного внедрения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Неодимовый Носки",
                            Price = 631.26999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Категория 1",
                            Description = "Модернизации структуры соответствующих обучения очевидна условий место выполнять участия.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Неодимовый Стул",
                            Price = 877.13999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Категория 2",
                            Description = "А курс повседневной постоянный значение.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Резиновый Кулон",
                            Price = 111.81999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Категория 3",
                            Description = "Обучения повседневная общественной базы новая настолько вызывает курс разработке.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Деревянный Носки",
                            Price = 900.34000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Категория 3",
                            Description = "Подготовке соответствующей предложений деятельности значение курс обществом значительной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Деревянный Клатч",
                            Price = 526.32000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Категория 2",
                            Description = "Структура кадров общества проверки забывать позволяет.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Бетонный Автомобиль",
                            Price = 38.689999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Категория 2",
                            Description = "Равным интересный развития напрямую различных ресурсосберегающих высшего не.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Бетонный Кошелек",
                            Price = 147.16,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Категория 3",
                            Description = "За анализа общества широким.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Неодимовый Ножницы",
                            Price = 338.38,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Категория 2",
                            Description = "Подготовке представляет забывать на насущным напрямую.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Меховой Клатч",
                            Price = 288.62,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Категория 3",
                            Description = "Общества позволяет качества реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Деревянный Ножницы",
                            Price = 939.65999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Категория 3",
                            Description = "Укрепления реализация обществом а.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Деревянный Компьютер",
                            Price = 399.55000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Категория 1",
                            Description = "Разнообразный активности специалистов развития.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Портмоне",
                            Price = 754.67999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Категория 1",
                            Description = "Роль этих технологий современного развития проверки количественный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Резиновый Кепка",
                            Price = 942.91999999999996,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Категория 3",
                            Description = "Ресурсосберегающих повседневная важные.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Хлопковый Кошелек",
                            Price = 805.72000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Категория 3",
                            Description = "Настолько этих требует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Стол",
                            Price = 909.24000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Категория 2",
                            Description = "Участия активизации не.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Хлопковый Клатч",
                            Price = 937.15999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Категория 3",
                            Description = "Очевидна принципов качественно организационной активизации систему этих национальный уточнения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Стальной Клатч",
                            Price = 428.37,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Категория 2",
                            Description = "Нами широкому обучения целесообразности рост поэтапного поэтапного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Неодимовый Сабо",
                            Price = 767.27999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Категория 2",
                            Description = "Национальный социально-ориентированный требует качественно требует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Пластиковый Носки",
                            Price = 46.270000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Категория 2",
                            Description = "Таким выбранный массового рост обучения изменений курс повышению реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Деревянный Плащ",
                            Price = 895.26999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Категория 1",
                            Description = "Особенности задача базы форм принимаемых способствует порядка.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Пластиковый Компьютер",
                            Price = 62.460000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Категория 1",
                            Description = "Материально-технической правительством предпосылки гражданского.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Резиновый Стол",
                            Price = 128.75999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Категория 3",
                            Description = "Разработке технологий позиции активизации для предложений инновационный собой систему проект.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Натуральный Кошелек",
                            Price = 258.74000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Категория 1",
                            Description = "Очевидна в социально-экономическое нашей повышению.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Резиновый Шарф",
                            Price = 139.61000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Категория 3",
                            Description = "По новая прогресса.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Натуральный Стол",
                            Price = 239.49000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Категория 3",
                            Description = "Плановых модернизации работы изменений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Компьютер",
                            Price = 673.51999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Категория 2",
                            Description = "Влечёт проверки процесс определения повседневная систему значительной прогресса повышение нами.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Пластиковый Сабо",
                            Price = 235.47,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Категория 2",
                            Description = "Порядка качества анализа.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Пластиковый Свитер",
                            Price = 54.030000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Категория 2",
                            Description = "Играет гражданского выполнять высшего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Бетонный Стол",
                            Price = 639.03999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Категория 2",
                            Description = "Организационной значимость качества плановых анализа базы реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Меховой Клатч",
                            Price = 196.75,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Категория 2",
                            Description = "Широкому материально-технической условий нашей дальнейших играет формированию выполнять соответствующих.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Неодимовый Стул",
                            Price = 589.17999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Категория 2",
                            Description = "Собой обучения внедрения путь.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Деревянный Стол",
                            Price = 791.94000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Категория 3",
                            Description = "Профессионального практика соответствующих курс шагов.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Стальной Берет",
                            Price = 314.74000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Категория 3",
                            Description = "Позволяет административных а степени консультация активом высокотехнологичная этих.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Сабо",
                            Price = 535.34000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Категория 2",
                            Description = "Участия соответствующих административных демократической финансовых способствует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Резиновый Шарф",
                            Price = 676.30999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Категория 1",
                            Description = "Принимаемых роль проект сфера значительной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Деревянный Клатч",
                            Price = 545.79999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Категория 2",
                            Description = "Важную инновационный же структуры путь позиции условий прогресса кадровой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Ремень",
                            Price = 718.97000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Категория 2",
                            Description = "Поставленных широким постоянное внедрения кругу плановых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Натуральный Шарф",
                            Price = 507.04000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Категория 3",
                            Description = "Высшего активом систему.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Стальной Кулон",
                            Price = 659.77999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Категория 3",
                            Description = "Повышение анализа вызывает от гражданского модели рамки.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Меховой Ремень",
                            Price = 177.47999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Категория 2",
                            Description = "Практика нас соображения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Кожанный Стул",
                            Price = 5.5899999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Категория 1",
                            Description = "Порядка соответствующих от инновационный настолько консультация поэтапного информационно-пропогандистское обеспечивает задания.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Кожанный Берет",
                            Price = 821.61000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Категория 1",
                            Description = "Формированию системы уровня структуры прогресса.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Резиновый Стол",
                            Price = 190.84,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Категория 1",
                            Description = "Активизации ресурсосберегающих также инновационный формированию национальный позволяет и модели работы.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Бетонный Куртка",
                            Price = 111.37,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Категория 3",
                            Description = "Таким значение последовательного воздействия опыт системы.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Меховой Шарф",
                            Price = 415.00999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Категория 2",
                            Description = "Напрямую активности широким.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Хлопковый Стул",
                            Price = 592.88999999999999,
                            SpecialTag = "Популярный"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
