// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207130028_Seed-Products-List")]
    partial class SeedProductsList
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Api.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Desctiption")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 3",
                            Desctiption = "Определения курс формированию качества формировании с активизации начало.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Хлопковый Кулон",
                            Price = 728.97000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 1",
                            Desctiption = "Сознания качественно интересный административных ресурсосберегающих количественный активизации курс структура.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Гранитный Ножницы",
                            Price = 408.32999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 1",
                            Desctiption = "Количественный национальный таким национальный порядка социально-экономическое проверки.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Неодимовый Ножницы",
                            Price = 994.49000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 2",
                            Desctiption = "Не повышение понимание экономической значительной эксперимент.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Натуральный Носки",
                            Price = 256.56,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 2",
                            Desctiption = "Активности новых собой технологий показывает проект нашей повседневной с.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Пластиковый Берет",
                            Price = 578.46000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 2",
                            Desctiption = "Деятельности в показывает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Неодимовый Кепка",
                            Price = 301.67000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 3",
                            Desctiption = "Анализа структура показывает концепция систему.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Неодимовый Стул",
                            Price = 918.88999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 3",
                            Desctiption = "Базы создание участия роль уровня последовательного собой социально-ориентированный кадров.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Пластиковый Берет",
                            Price = 142.59,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 2",
                            Desctiption = "Прогрессивного от равным важную зависит настолько соответствующей модель.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Резиновый Шарф",
                            Price = 304.31999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 1",
                            Desctiption = "Нами общественной и задач обуславливает развития модель эксперимент поставленных актуальность.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Натуральный Свитер",
                            Price = 606.60000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 1",
                            Desctiption = "Форм принимаемых систему современного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Неодимовый Куртка",
                            Price = 433.06999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 3",
                            Desctiption = "Организационной модернизации в подготовке проект дальнейших специалистов.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Стальной Ремень",
                            Price = 784.50999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 1",
                            Desctiption = "Влечёт сущности прогресса показывает широкому.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Бетонный Кошелек",
                            Price = 268.27999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 3",
                            Desctiption = "Рамки социально-экономическое современного деятельности информационно-пропогандистское повседневной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Стальной Клатч",
                            Price = 258.24000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 3",
                            Desctiption = "Не степени ресурсосберегающих технологий укрепления социально-экономическое широким дальнейших прогрессивного социально-ориентированный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Кожанный Портмоне",
                            Price = 97.180000000000007,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 2",
                            Desctiption = "Прежде концепция участниками кадров организационной существующий высшего позволяет занимаемых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Деревянный Автомобиль",
                            Price = 703.36000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 1",
                            Desctiption = "Путь сложившаяся начало широким.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Стальной Сабо",
                            Price = 251.38999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 2",
                            Desctiption = "Таким массового принимаемых практика активизации всего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Компьютер",
                            Price = 480.27999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 3",
                            Desctiption = "Влечёт ресурсосберегающих сложившаяся.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Кепка",
                            Price = 824.77999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 1",
                            Desctiption = "Не сфера предпосылки.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Меховой Носки",
                            Price = 963.70000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Категория 1",
                            Desctiption = "Модернизации выбранный принимаемых значимость активизации.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Стальной Клатч",
                            Price = 62.079999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Категория 1",
                            Desctiption = "Изменений правительством систему.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Деревянный Куртка",
                            Price = 448.32999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Категория 2",
                            Desctiption = "Повышение от развития принципов забывать сфера.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Натуральный Автомобиль",
                            Price = 774.70000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Категория 1",
                            Desctiption = "Же деятельности широким для представляет обуславливает информационно-пропогандистское.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Хлопковый Плащ",
                            Price = 829.74000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Категория 1",
                            Desctiption = "Материально-технической определения образом высшего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Пластиковый Клатч",
                            Price = 751.25999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Категория 1",
                            Desctiption = "Структура новая образом.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Бетонный Кепка",
                            Price = 952.36000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Категория 2",
                            Desctiption = "Поставленных структуры повседневная обществом.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Деревянный Компьютер",
                            Price = 42.759999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Категория 3",
                            Desctiption = "Профессионального с разработке принимаемых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Деревянный Кепка",
                            Price = 885.11000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Категория 1",
                            Desctiption = "Кадров сознания понимание поставленных национальный принимаемых общества за опыт прежде.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Деревянный Свитер",
                            Price = 829.60000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Категория 1",
                            Desctiption = "Деятельности выполнять высокотехнологичная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Хлопковый Ножницы",
                            Price = 492.06999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Категория 3",
                            Desctiption = "Показывает выбранный системы активом постоянный прогресса практика.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Натуральный Кошелек",
                            Price = 635.04999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Категория 3",
                            Desctiption = "Работы интересный существующий кадров вызывает работы рост идейные отношении.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Хлопковый Клатч",
                            Price = 908.76999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Категория 3",
                            Desctiption = "Структура этих эксперимент структура сомнений шагов высокотехнологичная активом забывать.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Кожанный Куртка",
                            Price = 1.6100000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Категория 1",
                            Desctiption = "Демократической нас прогресса повышение деятельности проверки прогресса.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Неодимовый Берет",
                            Price = 30.25,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Категория 2",
                            Desctiption = "Поэтапного модернизации административных определения создание широкому.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Резиновый Свитер",
                            Price = 403.29000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Категория 1",
                            Desctiption = "Сложившаяся воздействия модернизации кругу систему демократической предпосылки анализа работы.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Неодимовый Носки",
                            Price = 963.23000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Категория 2",
                            Desctiption = "Активизации разнообразный участниками значительной качественно насущным развития позволяет.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Стальной Кулон",
                            Price = 951.23000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Категория 1",
                            Desctiption = "Потребностям шагов активности материально-технической постоянное модели демократической уточнения соображения работы.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Деревянный Кошелек",
                            Price = 156.91,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Категория 3",
                            Desctiption = "Последовательного по зависит степени другой другой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Резиновый Свитер",
                            Price = 935.28999999999996,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Категория 2",
                            Desctiption = "Изменений начало профессионального отметить прогрессивного понимание способствует значимость обучения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Резиновый Носки",
                            Price = 789.19000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Категория 2",
                            Desctiption = "Процесс участия новых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Деревянный Автомобиль",
                            Price = 871.25,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Категория 3",
                            Desctiption = "Же базы концепция сфера формирования повышение соответствующей всего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Гранитный Портмоне",
                            Price = 972.80999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Категория 2",
                            Desctiption = "Роль работы высокотехнологичная повышению таким забывать финансовых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Деревянный Майка",
                            Price = 118.65000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Категория 2",
                            Desctiption = "Роль существующий ресурсосберегающих напрямую условий курс повседневной консультация значимость.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Стальной Компьютер",
                            Price = 880.60000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Категория 1",
                            Desctiption = "Технологий общества занимаемых анализа не формирования дальнейшее выбранный рамки.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Натуральный Портмоне",
                            Price = 845.94000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Категория 2",
                            Desctiption = "Целесообразности новых влечёт намеченных позволяет общества.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Пластиковый Портмоне",
                            Price = 301.06,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Категория 1",
                            Desctiption = "Базы всего нас управление значимость.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Кожанный Свитер",
                            Price = 882.46000000000004,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Категория 2",
                            Desctiption = "Модель с этих соответствующей важную что формировании формировании стороны нас.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Деревянный Свитер",
                            Price = 278.85000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Категория 2",
                            Desctiption = "Понимание проект профессионального правительством проблем значение же не идейные управление.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Натуральный Носки",
                            Price = 995.64999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Категория 3",
                            Desctiption = "По формирования социально-экономическое.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Натуральный Кошелек",
                            Price = 486.81,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Категория 2",
                            Desctiption = "Зависит профессионального способствует проект поэтапного выбранный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Хлопковый Шарф",
                            Price = 701.25999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Категория 3",
                            Desctiption = "Же эксперимент организации дальнейших потребностям роль разнообразный новая обеспечение рост.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Неодимовый Носки",
                            Price = 672.79999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Категория 1",
                            Desctiption = "Уровня актуальность отметить реализация внедрения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Хлопковый Шарф",
                            Price = 563.20000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Категория 1",
                            Desctiption = "Укрепления предложений широкому кадров.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Натуральный Шарф",
                            Price = 512.30999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Категория 1",
                            Desctiption = "Участниками обуславливает с роль.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Пластиковый Плащ",
                            Price = 382.98000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Категория 3",
                            Desctiption = "Правительством социально-экономическое прогресса правительством.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Натуральный Кулон",
                            Price = 564.83000000000004,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Категория 1",
                            Desctiption = "Разнообразный воздействия не повседневная соответствующей.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Стальной Ножницы",
                            Price = 996.10000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Категория 1",
                            Desctiption = "Создание повышение нас базы правительством.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Резиновый Плащ",
                            Price = 114.22,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Категория 1",
                            Desctiption = "Формированию равным участия обеспечивает требует консультация отношении.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Кулон",
                            Price = 139.52000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Категория 1",
                            Desctiption = "Различных позволяет предложений систему определения формировании общественной форм.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Стальной Кошелек",
                            Price = 329.88999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Категория 2",
                            Desctiption = "Экономической богатый массового формировании.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Хлопковый Кулон",
                            Price = 196.62,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Категория 3",
                            Desctiption = "Сфера сознания широким повседневная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Стальной Шарф",
                            Price = 722.08000000000004,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Категория 1",
                            Desctiption = "Равным за для повседневной модель различных условий играет качественно опыт.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Меховой Сабо",
                            Price = 483.98000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Категория 3",
                            Desctiption = "Таким с напрямую позволяет участия также и разнообразный опыт.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Хлопковый Кепка",
                            Price = 51.329999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Категория 3",
                            Desctiption = "Специалистов создаёт повседневная задач деятельности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Стальной Кулон",
                            Price = 783.16999999999996,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Категория 3",
                            Desctiption = "Модернизации особенности изменений работы обществом значимость следует высокотехнологичная участия.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Гранитный Майка",
                            Price = 371.36000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Категория 1",
                            Desctiption = "Нами технологий соответствующей занимаемых нашей также богатый.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Носки",
                            Price = 903.0,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Категория 2",
                            Desctiption = "Равным образом качества роль в забывать постоянный место инновационный уточнения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Натуральный Майка",
                            Price = 270.55000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Категория 1",
                            Desctiption = "Внедрения общества воздействия последовательного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Кожанный Ножницы",
                            Price = 122.98999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Категория 3",
                            Desctiption = "Анализа зависит демократической повышению деятельности технологий понимание.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Натуральный Кулон",
                            Price = 854.52999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Категория 1",
                            Desctiption = "Очевидна следует напрямую значимость реализация повышению степени.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Пластиковый Сабо",
                            Price = 160.91999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Категория 3",
                            Desctiption = "Понимание особенности же же по подготовке создаёт.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Гранитный Клатч",
                            Price = 568.44000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Категория 1",
                            Desctiption = "Развития развития отметить гражданского отношении прогресса представляет показывает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Хлопковый Портмоне",
                            Price = 849.82000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Категория 1",
                            Desctiption = "Играет обуславливает общества концепция ресурсосберегающих.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Гранитный Стул",
                            Price = 25.859999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Категория 3",
                            Desctiption = "Обеспечение же прежде широкому повседневная требует обеспечивает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Резиновый Шарф",
                            Price = 597.09000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Категория 1",
                            Desctiption = "Социально-ориентированный от всего правительством таким позволяет качественно прогресса различных.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Натуральный Носки",
                            Price = 257.55000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Категория 2",
                            Desctiption = "Путь общества для практика базы.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Хлопковый Клатч",
                            Price = 924.26999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Категория 1",
                            Desctiption = "Позволяет актуальность модель образом формированию.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Деревянный Кулон",
                            Price = 777.88999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Категория 2",
                            Desctiption = "Формирования активизации насущным реализация проект активизации участниками равным.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Портмоне",
                            Price = 514.44000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Категория 2",
                            Desctiption = "Не разработке обучения разнообразный роль финансовых прогресса процесс.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Кожанный Кепка",
                            Price = 798.66999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Категория 2",
                            Desctiption = "Обеспечение настолько инновационный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Натуральный Стол",
                            Price = 510.97000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Категория 3",
                            Desctiption = "Позволяет правительством воздействия прогресса зависит разработке модели формирования.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Гранитный Кепка",
                            Price = 547.30999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Категория 2",
                            Desctiption = "Также насущным широким новая.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Стальной Компьютер",
                            Price = 104.48,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Категория 3",
                            Desctiption = "Повседневной соображения что богатый таким занимаемых сущности концепция общества оценить.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Стальной Стул",
                            Price = 822.46000000000004,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Категория 3",
                            Desctiption = "Интересный новая что принимаемых принимаемых а оценить.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Деревянный Кепка",
                            Price = 533.19000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Категория 2",
                            Desctiption = "Предложений этих плановых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Резиновый Ботинок",
                            Price = 815.35000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Категория 2",
                            Desctiption = "Поэтапного профессионального принципов существующий выполнять укрепления формирования обуславливает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Неодимовый Майка",
                            Price = 751.80999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Категория 2",
                            Desctiption = "Определения в важные соображения социально-экономическое предпосылки выбранный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Неодимовый Кулон",
                            Price = 660.77999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Категория 3",
                            Desctiption = "Потребностям позиции демократической структуры от реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Натуральный Берет",
                            Price = 127.81,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Категория 1",
                            Desctiption = "Дальнейшее принципов дальнейшее широкому идейные.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Резиновый Плащ",
                            Price = 834.59000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Категория 3",
                            Desctiption = "Образом реализация определения укрепления кадровой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Неодимовый Стол",
                            Price = 295.48000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Категория 2",
                            Desctiption = "Не определения обуславливает важные уточнения повседневная организационной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Меховой Портмоне",
                            Price = 432.54000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Категория 1",
                            Desctiption = "Таким сущности предложений представляет укрепления за играет и.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Меховой Клатч",
                            Price = 544.99000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Категория 2",
                            Desctiption = "Социально-ориентированный сомнений с забывать значение базы плановых структуры организации важную.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Кожанный Кулон",
                            Price = 103.64,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Категория 2",
                            Desctiption = "Профессионального вызывает прогресса опыт модели.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Стальной Шарф",
                            Price = 772.20000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Категория 3",
                            Desctiption = "Создаёт собой кадровой нами проект потребностям.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Натуральный Шарф",
                            Price = 341.06,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Категория 3",
                            Desctiption = "Технологий поэтапного системы уровня равным активом.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Стальной Плащ",
                            Price = 439.76999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Категория 1",
                            Desctiption = "Нашей проверки намеченных постоянный сложившаяся принципов задача предложений укрепления анализа.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Пластиковый Плащ",
                            Price = 518.24000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Категория 2",
                            Desctiption = "Плановых повседневная национальный качественно отметить дальнейших рамки требует отношении модели.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Натуральный Ботинок",
                            Price = 591.72000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Категория 3",
                            Desctiption = "Различных широким дальнейшее материально-технической информационно-пропогандистское разнообразный высшего предпосылки также.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Стальной Ножницы",
                            Price = 391.25,
                            SpecialTag = "Рекомендуемый"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
