// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251227155224_Add-Shopping-Cart-And-Cart")]
    partial class AddShoppingCartAndCart
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Api.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Api.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 1",
                            Description = "Уточнения системы поставленных способствует уровня не различных форм предложений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Бетонный Ножницы",
                            Price = 33.939999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 2",
                            Description = "Же высшего выполнять деятельности равным управление.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Стальной Кулон",
                            Price = 516.69000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 3",
                            Description = "Качественно позиции предпосылки технологий прежде по инновационный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Кожанный Шарф",
                            Price = 441.54000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 2",
                            Description = "Поставленных мира повышение.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Кожанный Плащ",
                            Price = 291.33999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 1",
                            Description = "Информационно-пропогандистское участниками повышение таким не.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Хлопковый Кулон",
                            Price = 29.219999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 1",
                            Description = "Рост следует демократической повышению качества предпосылки финансовых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Хлопковый Кошелек",
                            Price = 166.38,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 2",
                            Description = "Инновационный общества задача.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Натуральный Стол",
                            Price = 924.13999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 1",
                            Description = "Кадровой проблем позиции в работы же укрепления забывать.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Меховой Стол",
                            Price = 490.30000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 2",
                            Description = "Поэтапного показывает консультация нами.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Гранитный Стул",
                            Price = 322.85000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 1",
                            Description = "Что структуры экономической постоянное нас сущности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Натуральный Берет",
                            Price = 857.75,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 2",
                            Description = "Консультация активности организации важную собой управление следует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Гранитный Плащ",
                            Price = 569.84000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 3",
                            Description = "Оценить направлений влечёт обеспечение другой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Неодимовый Ботинок",
                            Price = 380.35000000000002,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 1",
                            Description = "Базы консультация реализация поэтапного высшего обществом.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Гранитный Кепка",
                            Price = 616.0,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 2",
                            Description = "Информационно-пропогандистское соответствующих подготовке качества сложившаяся экономической.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Хлопковый Майка",
                            Price = 590.69000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 2",
                            Description = "Существующий национальный эксперимент особенности от.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Деревянный Кепка",
                            Price = 204.72999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 1",
                            Description = "Понимание широким и задач проблем целесообразности проект.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Деревянный Автомобиль",
                            Price = 691.5,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 2",
                            Description = "Поэтапного системы плановых путь реализация также намеченных подготовке.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Меховой Носки",
                            Price = 639.12,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 1",
                            Description = "Насущным отношении сфера качества реализация.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Резиновый Ботинок",
                            Price = 175.09999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 3",
                            Description = "Занимаемых место постоянный позиции постоянное играет кадровой базы.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Гранитный Портмоне",
                            Price = 876.88999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 3",
                            Description = "Особенности управление сущности кругу таким деятельности сущности плановых базы социально-ориентированный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Резиновый Портмоне",
                            Price = 236.91,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Категория 2",
                            Description = "Обуславливает материально-технической вызывает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Натуральный Берет",
                            Price = 594.28999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Категория 3",
                            Description = "Принципов представляет правительством на не соответствующей другой практика модели.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Кожанный Шарф",
                            Price = 940.07000000000005,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Категория 3",
                            Description = "Опыт участия укрепления для обуславливает для специалистов сомнений прогресса.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Неодимовый Компьютер",
                            Price = 282.38999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Категория 1",
                            Description = "Занимаемых правительством участниками всего внедрения нами целесообразности последовательного различных разработке.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Меховой Стул",
                            Price = 297.95999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Категория 1",
                            Description = "По путь структура позволяет прежде роль богатый.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Неодимовый Кулон",
                            Price = 560.05999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Категория 3",
                            Description = "Прежде потребностям образом качественно.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Кожанный Стул",
                            Price = 890.65999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Категория 1",
                            Description = "Прогресса определения модели а влечёт кругу базы управление социально-экономическое специалистов.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Деревянный Кошелек",
                            Price = 898.38999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Категория 2",
                            Description = "Предложений различных последовательного позволяет следует направлений проект.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Меховой Кошелек",
                            Price = 243.02000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Категория 3",
                            Description = "Проект стороны повышение структура.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Неодимовый Плащ",
                            Price = 695.92999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Категория 1",
                            Description = "Начало уточнения важные роль определения позволяет высокотехнологичная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Деревянный Свитер",
                            Price = 353.92000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Категория 1",
                            Description = "Очевидна гражданского соответствующих курс технологий таким выбранный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Бетонный Сабо",
                            Price = 621.87,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Категория 1",
                            Description = "Деятельности постоянный правительством позволяет дальнейших.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Кожанный Ножницы",
                            Price = 510.75999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Категория 1",
                            Description = "Обуславливает качественно кадров.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Кожанный Ботинок",
                            Price = 174.49000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Категория 1",
                            Description = "Массового систему стороны забывать.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Плащ",
                            Price = 411.63999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Категория 3",
                            Description = "Создание интересный укрепления соответствующих высокотехнологичная форм порядка обеспечивает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Натуральный Портмоне",
                            Price = 41.219999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Категория 1",
                            Description = "Высокотехнологичная богатый путь разработке качества насущным.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Неодимовый Автомобиль",
                            Price = 662.94000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Категория 2",
                            Description = "А современного обществом также административных воздействия структуры процесс последовательного широким.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Хлопковый Автомобиль",
                            Price = 484.23000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Категория 2",
                            Description = "Важную социально-экономическое постоянный кругу базы показывает однако на.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Деревянный Ремень",
                            Price = 26.210000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Категория 2",
                            Description = "Порядка обучения широкому.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Меховой Кулон",
                            Price = 614.87,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Категория 1",
                            Description = "Соображения организационной однако управление формировании рост.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Неодимовый Шарф",
                            Price = 161.80000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Категория 1",
                            Description = "Принимаемых прогрессивного показывает социально-ориентированный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Гранитный Носки",
                            Price = 853.90999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Категория 1",
                            Description = "Сознания рост дальнейших формирования создание обеспечение активности мира.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Меховой Свитер",
                            Price = 10.85,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Категория 3",
                            Description = "Дальнейшее отношении кадров.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Меховой Портмоне",
                            Price = 15.460000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Категория 1",
                            Description = "Системы участия национальный выполнять.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Кожанный Клатч",
                            Price = 995.95000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Категория 1",
                            Description = "Количественный что важную активизации следует роль социально-ориентированный сознания стороны нами.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Резиновый Кулон",
                            Price = 475.94999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Категория 1",
                            Description = "Насущным массового вызывает.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Портмоне",
                            Price = 476.10000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Категория 1",
                            Description = "Участия повседневная условий важные стороны представляет не.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Натуральный Носки",
                            Price = 445.04000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Категория 1",
                            Description = "Инновационный важную сомнений же.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Хлопковый Кепка",
                            Price = 184.58000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Категория 3",
                            Description = "Значимость реализация базы кадров шагов изменений сфера направлений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Неодимовый Майка",
                            Price = 546.52999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Категория 1",
                            Description = "Создаёт социально-экономическое другой соображения новых актуальность.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Натуральный Стол",
                            Price = 920.27999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Категория 2",
                            Description = "Отметить анализа внедрения модели формирования шагов насущным другой место.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Гранитный Стол",
                            Price = 57.590000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Категория 1",
                            Description = "Высокотехнологичная что плановых обществом процесс ресурсосберегающих уточнения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Стальной Портмоне",
                            Price = 899.10000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Категория 3",
                            Description = "Повседневная консультация практика поставленных очевидна.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Гранитный Носки",
                            Price = 490.74000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Категория 3",
                            Description = "Задача активом важную задач широким настолько курс и.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Хлопковый Компьютер",
                            Price = 237.37,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Категория 1",
                            Description = "Прогрессивного анализа модернизации принципов плановых повседневная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Деревянный Кулон",
                            Price = 154.25999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Категория 1",
                            Description = "Форм инновационный создание активизации насущным повседневной современного проблем уточнения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Ботинок",
                            Price = 149.25999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Категория 3",
                            Description = "Организационной зависит соответствующих укрепления разнообразный модернизации укрепления работы эксперимент кадровой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Пластиковый Автомобиль",
                            Price = 198.53999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Категория 1",
                            Description = "Высокотехнологичная задач демократической значимость.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Натуральный Кулон",
                            Price = 444.02999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Категория 1",
                            Description = "Намеченных профессионального системы социально-ориентированный прогрессивного принимаемых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Пластиковый Сабо",
                            Price = 827.79999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Категория 2",
                            Description = "Сфера важные понимание экономической участниками шагов гражданского же соответствующей.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Бетонный Портмоне",
                            Price = 14.869999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Категория 3",
                            Description = "Поэтапного дальнейшее повышение изменений оценить степени существующий прогресса таким.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Неодимовый Стол",
                            Price = 496.27999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Категория 2",
                            Description = "Экономической формирования другой сущности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Пластиковый Компьютер",
                            Price = 709.92999999999995,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Категория 1",
                            Description = "Значимость предпосылки уровня нашей для позиции для забывать целесообразности рост.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Стальной Кошелек",
                            Price = 309.30000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Категория 3",
                            Description = "Стороны зависит уточнения от принципов.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Гранитный Куртка",
                            Price = 898.12,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Категория 3",
                            Description = "Рост активности постоянное участниками что шагов внедрения соображения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Меховой Майка",
                            Price = 80.879999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Категория 1",
                            Description = "Структура экономической повышение рост укрепления структуры способствует мира участия задач.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Меховой Клатч",
                            Price = 523.07000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Категория 3",
                            Description = "Последовательного оценить занимаемых воздействия уровня.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Бетонный Ножницы",
                            Price = 274.17000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Категория 2",
                            Description = "Также другой соображения национальный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Неодимовый Кошелек",
                            Price = 115.56,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Категория 2",
                            Description = "Широкому новая высокотехнологичная задач от.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Хлопковый Ремень",
                            Price = 28.359999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Категория 2",
                            Description = "Ресурсосберегающих для сфера национальный структуры разработке плановых проект.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Гранитный Портмоне",
                            Price = 772.41999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Категория 1",
                            Description = "Важные базы высшего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Гранитный Свитер",
                            Price = 651.07000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Категория 1",
                            Description = "Профессионального задача поэтапного принимаемых административных консультация форм профессионального.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Пластиковый Свитер",
                            Price = 622.75999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Категория 3",
                            Description = "Значение поэтапного развития играет место сложившаяся плановых современного новых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Бетонный Куртка",
                            Price = 637.50999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Категория 3",
                            Description = "Требует что разработке создаёт важную сознания этих соображения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Неодимовый Плащ",
                            Price = 320.31999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Категория 3",
                            Description = "Проект консультация образом определения модернизации предпосылки деятельности задача что постоянное.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Пластиковый Автомобиль",
                            Price = 637.87,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Категория 1",
                            Description = "Порядка социально-экономическое постоянное специалистов информационно-пропогандистское поэтапного структуры прогрессивного кадровой значительной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Клатч",
                            Price = 549.75,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Категория 3",
                            Description = "Последовательного последовательного отметить.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Кожанный Клатч",
                            Price = 721.59000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Категория 1",
                            Description = "Место инновационный повышению важную организации соответствующих проект.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Кепка",
                            Price = 348.73000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Категория 2",
                            Description = "Широким принципов повседневной деятельности условий по равным развития.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Пластиковый Носки",
                            Price = 86.719999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Категория 1",
                            Description = "Не порядка проект различных базы организации технологий.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Деревянный Свитер",
                            Price = 246.69999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Категория 2",
                            Description = "Управление организационной постоянное структура настолько принципов модели.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Неодимовый Кошелек",
                            Price = 937.02999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Категория 3",
                            Description = "Оценить всего ресурсосберегающих зависит нашей задача.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Натуральный Майка",
                            Price = 831.10000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Категория 1",
                            Description = "Же определения последовательного сомнений что другой способствует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Деревянный Сабо",
                            Price = 462.38999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Категория 2",
                            Description = "Форм в участия разработке требует обуславливает значительной оценить всего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Кожанный Свитер",
                            Price = 647.09000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Категория 2",
                            Description = "Позволяет стороны повседневная плановых широким.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Неодимовый Сабо",
                            Price = 769.16999999999996,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Категория 2",
                            Description = "Обуславливает сложившаяся деятельности повседневной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Бетонный Компьютер",
                            Price = 84.290000000000006,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Категория 3",
                            Description = "Формированию нас количественный последовательного практика играет курс всего представляет богатый.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Бетонный Компьютер",
                            Price = 598.89999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Категория 2",
                            Description = "Таким уровня и проблем прежде обуславливает задач также сознания создаёт.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Хлопковый Кепка",
                            Price = 486.42000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Категория 3",
                            Description = "Проверки дальнейшее демократической экономической проверки высокотехнологичная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Стальной Плащ",
                            Price = 473.26999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Категория 2",
                            Description = "Этих показывает предпосылки с образом модели повседневная за различных значимость.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Свитер",
                            Price = 333.5,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Категория 1",
                            Description = "Консультация организационной сознания ресурсосберегающих дальнейшее за.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Резиновый Стул",
                            Price = 661.97000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Категория 2",
                            Description = "Не намеченных форм.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Деревянный Куртка",
                            Price = 888.51999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Категория 1",
                            Description = "Рамки оценить оценить целесообразности рост.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Деревянный Ремень",
                            Price = 884.44000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Категория 3",
                            Description = "Гражданского активом структуры уровня работы повседневная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Пластиковый Носки",
                            Price = 19.0,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Категория 3",
                            Description = "Выбранный последовательного уточнения участия занимаемых последовательного новых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Бетонный Свитер",
                            Price = 547.13999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Категория 3",
                            Description = "Обеспечение и на экономической прежде повседневная по подготовке.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Стальной Кулон",
                            Price = 436.44999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Категория 2",
                            Description = "Качественно технологий изменений формировании соответствующей социально-экономическое.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Меховой Клатч",
                            Price = 114.94,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Категория 3",
                            Description = "Определения рост различных и намеченных с целесообразности эксперимент.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Пластиковый Кепка",
                            Price = 932.46000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Категория 2",
                            Description = "Шагов прогрессивного демократической развития сущности принимаемых структуры понимание.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Пластиковый Автомобиль",
                            Price = 856.89999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Категория 1",
                            Description = "Не поэтапного поэтапного задания идейные укрепления прежде различных.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Кошелек",
                            Price = 465.63,
                            SpecialTag = "Новинка"
                        });
                });

            modelBuilder.Entity("Api.Model.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Api.Model.CartItem", b =>
                {
                    b.HasOne("Api.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.ShoppingCart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Model.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
