// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251228162049_Add_OrderDetails_And_OrderHeaders")]
    partial class Add_OrderDetails_And_OrderHeaders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Model.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Api.Model.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("Api.Model.OrderHeader", b =>
                {
                    b.Property<int>("OrderHeaderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderHeaderId"));

                    b.Property<string>("AppUserId")
                        .HasColumnType("text");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OrderDataTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("OrderTotalAmount")
                        .HasColumnType("double precision");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("TotalCount")
                        .HasColumnType("integer");

                    b.HasKey("OrderHeaderId");

                    b.HasIndex("AppUserId");

                    b.ToTable("OrderHeaders");
                });

            modelBuilder.Entity("Api.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Image")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("SpecialTag")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Категория 2",
                            Description = "Показывает сложившаяся различных последовательного системы социально-экономическое курс.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Хлопковый Шарф",
                            Price = 105.31,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Категория 1",
                            Description = "Важную ресурсосберегающих за.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Хлопковый Плащ",
                            Price = 615.52999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Категория 3",
                            Description = "Гражданского кадровой управление высокотехнологичная существующий эксперимент.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Меховой Портмоне",
                            Price = 165.97,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Категория 1",
                            Description = "Сложившаяся специалистов проверки определения широкому требует вызывает образом важную повышению.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Гранитный Свитер",
                            Price = 256.64999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Категория 1",
                            Description = "Кадровой забывать количественный административных обуславливает кадровой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Меховой Свитер",
                            Price = 540.72000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Категория 1",
                            Description = "За реализация за кругу существующий профессионального таким прежде.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Стальной Берет",
                            Price = 760.64999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Категория 2",
                            Description = "Высокотехнологичная обществом позволяет представляет за в задач также роль.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Кожанный Ножницы",
                            Price = 568.90999999999997,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Категория 2",
                            Description = "Рамки очевидна понимание.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Гранитный Кепка",
                            Price = 513.46000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Категория 2",
                            Description = "Сущности что правительством занимаемых позволяет кадров.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Хлопковый Кепка",
                            Price = 882.38,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Категория 1",
                            Description = "Важные структура богатый концепция структура формированию сущности новая.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Меховой Ремень",
                            Price = 849.74000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Категория 3",
                            Description = "Всего на выбранный дальнейших требует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Пластиковый Майка",
                            Price = 632.5,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Категория 2",
                            Description = "Целесообразности дальнейшее социально-экономическое поэтапного форм обществом кадров создаёт занимаемых настолько.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Резиновый Шарф",
                            Price = 319.44,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Категория 2",
                            Description = "Повседневной по также формировании намеченных соответствующих богатый также.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Неодимовый Сабо",
                            Price = 319.31999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Категория 3",
                            Description = "Структура в напрямую от модели современного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Стальной Кулон",
                            Price = 450.39999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Категория 3",
                            Description = "Отношении нами активизации.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Резиновый Автомобиль",
                            Price = 220.83000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Категория 1",
                            Description = "Качественно укрепления реализация намеченных однако.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Стальной Ножницы",
                            Price = 906.48000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Категория 2",
                            Description = "Позволяет широким кадровой общества.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Хлопковый Куртка",
                            Price = 183.84999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Категория 2",
                            Description = "Административных высшего по.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Бетонный Ножницы",
                            Price = 216.13,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Категория 2",
                            Description = "Уровня форм мира занимаемых обществом демократической играет нами сознания.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Хлопковый Кепка",
                            Price = 895.53999999999996,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Категория 3",
                            Description = "Систему социально-ориентированный всего настолько.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Пластиковый Сабо",
                            Price = 545.12,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Категория 3",
                            Description = "Позволяет обеспечивает определения плановых значительной задания нами.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Кожанный Клатч",
                            Price = 226.43000000000001,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Категория 2",
                            Description = "Управление за укрепления оценить практика.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Гранитный Клатч",
                            Price = 809.02999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Категория 1",
                            Description = "Консультация систему высшего работы организации задач по стороны же.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Меховой Берет",
                            Price = 125.59999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Категория 3",
                            Description = "Уточнения модернизации определения на правительством оценить настолько структура высшего насущным.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Натуральный Ботинок",
                            Price = 34.729999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Категория 1",
                            Description = "Социально-ориентированный модель представляет и влечёт уточнения зависит.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Меховой Ножницы",
                            Price = 437.75,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Категория 2",
                            Description = "Разработке идейные уровня для повышению общества этих сознания проблем.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Меховой Плащ",
                            Price = 737.10000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Категория 3",
                            Description = "И специалистов условий выбранный за формировании.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Кожанный Автомобиль",
                            Price = 817.13,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Категория 2",
                            Description = "Участниками структуры кадров.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Кожанный Кошелек",
                            Price = 614.65999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Категория 2",
                            Description = "Участниками другой качества модели массового управление и.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Натуральный Майка",
                            Price = 885.80999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Категория 1",
                            Description = "Форм целесообразности настолько.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Бетонный Куртка",
                            Price = 728.40999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Категория 2",
                            Description = "Профессионального следует финансовых богатый процесс курс.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Кожанный Ботинок",
                            Price = 401.62,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Категория 2",
                            Description = "Для консультация формировании оценить понимание развития.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Деревянный Кошелек",
                            Price = 214.41,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Категория 3",
                            Description = "Нами системы курс актуальность вызывает а количественный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Неодимовый Свитер",
                            Price = 924.36000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Категория 3",
                            Description = "Стороны целесообразности представляет задания и широким путь количественный принимаемых последовательного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Натуральный Свитер",
                            Price = 143.30000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Категория 3",
                            Description = "Значительной активизации предложений реализация консультация же играет сомнений потребностям.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Деревянный Стул",
                            Price = 954.61000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Категория 1",
                            Description = "Сфера концепция настолько проект.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Стальной Плащ",
                            Price = 512.84000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Категория 3",
                            Description = "Плановых значение повышению структуры.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Деревянный Автомобиль",
                            Price = 46.210000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Категория 2",
                            Description = "Правительством кругу нас управление формирования новая кругу понимание на.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Натуральный Куртка",
                            Price = 331.38,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Категория 2",
                            Description = "Задания материально-технической новая с нами и нашей структура.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Кожанный Кепка",
                            Price = 908.08000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Категория 2",
                            Description = "Структура новых проверки направлений выбранный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Меховой Стул",
                            Price = 711.80999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Категория 3",
                            Description = "Намеченных создаёт гражданского внедрения форм обществом подготовке системы организационной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Гранитный Свитер",
                            Price = 764.19000000000005,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Категория 1",
                            Description = "Ресурсосберегающих поэтапного существующий.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Натуральный Ремень",
                            Price = 112.58,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Категория 3",
                            Description = "Структура плановых сложившаяся массового.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Резиновый Ремень",
                            Price = 60.649999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Категория 3",
                            Description = "Нами национальный вызывает условий широким подготовке идейные поставленных информационно-пропогандистское массового.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Меховой Шарф",
                            Price = 373.45999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Категория 3",
                            Description = "Формировании экономической что специалистов практика определения создание.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Гранитный Сабо",
                            Price = 992.28999999999996,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Категория 1",
                            Description = "Этих зависит в создание сфера.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Деревянный Берет",
                            Price = 539.58000000000004,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Категория 2",
                            Description = "Дальнейших сложившаяся забывать активом отношении высокотехнологичная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Бетонный Ботинок",
                            Price = 793.70000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Категория 3",
                            Description = "Существующий процесс новых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Бетонный Стол",
                            Price = 166.49000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Категория 1",
                            Description = "Постоянное формировании новых обеспечивает формировании формировании задач.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Стальной Ботинок",
                            Price = 331.79000000000002,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Категория 3",
                            Description = "На условий формирования обществом.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Гранитный Ботинок",
                            Price = 182.91999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Категория 2",
                            Description = "Сфера понимание рост.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Резиновый Майка",
                            Price = 341.31,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Категория 2",
                            Description = "Модель по рамки технологий.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Кожанный Носки",
                            Price = 657.78999999999996,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Категория 1",
                            Description = "Кругу таким нас.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Неодимовый Стул",
                            Price = 533.33000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Категория 1",
                            Description = "Укрепления демократической направлений модернизации различных в.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Кожанный Носки",
                            Price = 568.24000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Категория 2",
                            Description = "Рамки зависит воздействия отношении базы для проект мира широким активом.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Деревянный Ножницы",
                            Price = 596.13999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Категория 2",
                            Description = "Укрепления активности гражданского.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Меховой Носки",
                            Price = 457.38999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Категория 3",
                            Description = "Постоянное кадровой прогресса требует кругу деятельности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Бетонный Автомобиль",
                            Price = 258.88,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Категория 2",
                            Description = "Информационно-пропогандистское прогресса проверки соответствующей выбранный роль.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Стальной Сабо",
                            Price = 144.11000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Категория 3",
                            Description = "Формирования соответствующих различных разнообразный качественно административных организационной.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Гранитный Стол",
                            Price = 227.09999999999999,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Категория 3",
                            Description = "Условий инновационный ресурсосберегающих правительством организационной внедрения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Кожанный Майка",
                            Price = 934.45000000000005,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Категория 2",
                            Description = "Специалистов другой модели.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Резиновый Майка",
                            Price = 334.33999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Категория 2",
                            Description = "Постоянный задач общества общественной важные процесс базы целесообразности.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Деревянный Стол",
                            Price = 647.52999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Категория 3",
                            Description = "Таким задач специалистов существующий массового другой.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Резиновый Майка",
                            Price = 522.0,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Категория 3",
                            Description = "Условий значительной дальнейшее обеспечение сознания существующий важную способствует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Стальной Ножницы",
                            Price = 388.86000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Категория 3",
                            Description = "Важную модели качества материально-технической способствует курс богатый всего.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Бетонный Кепка",
                            Price = 715.97000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Категория 3",
                            Description = "Проект соображения этих соображения с.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Натуральный Кошелек",
                            Price = 587.86000000000001,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Категория 2",
                            Description = "Важные степени показывает в нами технологий работы современного соответствующей способствует.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Стальной Кулон",
                            Price = 523.90999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Категория 3",
                            Description = "Организационной рост собой для выполнять место начало.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Бетонный Кошелек",
                            Price = 318.06,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Категория 2",
                            Description = "Зависит формированию сфера для начало активизации отношении.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Натуральный Стол",
                            Price = 36.07,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Категория 2",
                            Description = "Внедрения другой инновационный национальный занимаемых понимание сомнений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Хлопковый Свитер",
                            Price = 880.58000000000004,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Категория 1",
                            Description = "Кадровой другой обуславливает особенности отношении выбранный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Бетонный Стол",
                            Price = 229.84,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Категория 1",
                            Description = "Технологий сфера уточнения проверки оценить на укрепления существующий национальный технологий.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Кожанный Компьютер",
                            Price = 932.47000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Категория 1",
                            Description = "Кадров нашей выбранный понимание структуры.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Меховой Плащ",
                            Price = 589.55999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Категория 1",
                            Description = "Важную повседневной организационной изменений сомнений.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Деревянный Майка",
                            Price = 943.71000000000004,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Категория 3",
                            Description = "Значимость позиции сложившаяся плановых обуславливает повышение другой очевидна.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Эргономичный Стальной Клатч",
                            Price = 156.44,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Категория 1",
                            Description = "Разработке обуславливает важные богатый.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Кожанный Шарф",
                            Price = 26.93,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Категория 1",
                            Description = "Курс укрепления дальнейшее равным на формирования административных намеченных выбранный принимаемых.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Кожанный Сабо",
                            Price = 345.14999999999998,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Категория 2",
                            Description = "Материально-технической соответствующих экономической определения зависит курс эксперимент различных.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Практичный Стальной Портмоне",
                            Price = 688.75999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Категория 2",
                            Description = "Существующий создаёт направлений особенности определения по потребностям.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Лоснящийся Пластиковый Автомобиль",
                            Price = 611.39999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Категория 3",
                            Description = "Широкому соображения в широкому богатый.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Кожанный Портмоне",
                            Price = 470.05000000000001,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Категория 1",
                            Description = "В внедрения уровня таким за обучения способствует прежде социально-ориентированный место.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Гранитный Клатч",
                            Price = 925.65999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Категория 3",
                            Description = "Плановых материально-технической влечёт.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Кожанный Автомобиль",
                            Price = 96.239999999999995,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Категория 1",
                            Description = "На подготовке участия.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Фантастический Меховой Клатч",
                            Price = 490.69999999999999,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Категория 1",
                            Description = "Системы уровня общественной организационной различных информационно-пропогандистское.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Стальной Компьютер",
                            Price = 696.29999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Категория 1",
                            Description = "Базы укрепления управление демократической.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Натуральный Клатч",
                            Price = 670.84000000000003,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Категория 1",
                            Description = "Также а национальный важную позволяет социально-ориентированный выбранный анализа.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Натуральный Кепка",
                            Price = 645.67999999999995,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Категория 3",
                            Description = "Играет создаёт модернизации.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Бетонный Берет",
                            Price = 773.90999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Категория 1",
                            Description = "Стороны значение повседневная.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Грубый Бетонный Берет",
                            Price = 904.40999999999997,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Категория 2",
                            Description = "Актуальность высшего последовательного место массового поэтапного разнообразный однако.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Деревянный Ремень",
                            Price = 575.51999999999998,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Категория 1",
                            Description = "Принципов задания обществом ресурсосберегающих формировании социально-экономическое сфера очевидна.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Деревянный Портмоне",
                            Price = 6.0899999999999999,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Категория 2",
                            Description = "И различных демократической от реализация технологий обуславливает отношении разработке последовательного.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Маленький Стальной Портмоне",
                            Price = 599.34000000000003,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Категория 2",
                            Description = "Другой практика количественный место.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Пластиковый Клатч",
                            Price = 514.38,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Категория 2",
                            Description = "Определения всего значение социально-ориентированный.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Интеллектуальный Хлопковый Ботинок",
                            Price = 607.39999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Категория 1",
                            Description = "Место модернизации обуславливает гражданского работы на значительной сущности актуальность.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Потрясающий Пластиковый Ножницы",
                            Price = 707.73000000000002,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Категория 1",
                            Description = "Очевидна напрямую определения на уточнения.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Пластиковый Стул",
                            Price = 782.14999999999998,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Категория 2",
                            Description = "Процесс модернизации воздействия сфера поэтапного повышению подготовке.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Большой Гранитный Ножницы",
                            Price = 14.85,
                            SpecialTag = "Рекомендуемый"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Категория 1",
                            Description = "Кадровой уточнения не путь.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Невероятный Меховой Ремень",
                            Price = 400.66000000000003,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Категория 2",
                            Description = "Особенности соответствующей повседневная поставленных забывать порядка.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Натуральный Кепка",
                            Price = 664.28999999999996,
                            SpecialTag = "Новинка"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Категория 1",
                            Description = "Административных форм определения обеспечение существующий.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Свободный Кожанный Берет",
                            Price = 39.659999999999997,
                            SpecialTag = "Популярный"
                        },
                        new
                        {
                            Id = 100,
                            Category = "Категория 3",
                            Description = "Порядка процесс поэтапного специалистов соответствующих образом демократической новая для насущным.",
                            Image = "https://cataas.com/cat?width=100&cat?height=:100",
                            Name = "Великолепный Деревянный Сабо",
                            Price = 756.08000000000004,
                            SpecialTag = "Новинка"
                        });
                });

            modelBuilder.Entity("Api.Model.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("Api.ModelDto.OrderDetails", b =>
                {
                    b.Property<int>("OrderDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderDetailId"));

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderHeaderId")
                        .HasColumnType("integer");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderDetailId");

                    b.HasIndex("OrderHeaderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderDetails");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Api.Model.CartItem", b =>
                {
                    b.HasOne("Api.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.ShoppingCart", null)
                        .WithMany("CartItems")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Api.Model.OrderHeader", b =>
                {
                    b.HasOne("Api.Model.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("AppUserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Api.ModelDto.OrderDetails", b =>
                {
                    b.HasOne("Api.Model.OrderHeader", null)
                        .WithMany("OrderDetailItems")
                        .HasForeignKey("OrderHeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Api.Model.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Api.Model.OrderHeader", b =>
                {
                    b.Navigation("OrderDetailItems");
                });

            modelBuilder.Entity("Api.Model.ShoppingCart", b =>
                {
                    b.Navigation("CartItems");
                });
#pragma warning restore 612, 618
        }
    }
}
